export const handler = (req, res) => {
  return new Response(JSON.stringify({
      providers: [
        'https://smallcamp.art',
        'https://sfba.social',
        'https://tidy.camp',
        'https://merveilles.town',
        'https://fosstodon.org',
        'https://front-end.social',
        'https://mastodon.social',
        'https://mastodon.art',
        'https://rage.love',
        'https://social.coop',
        'https://maique.lol',
        'https://mastodon.ar.al',
        'https://hachyderm.io',
        'https://bell.bz',
        'https://brands.town',
        'https://social.linux.pizza',
        'https://universeodon.com',
        'https://hackny.social',
        'https://mastodon.archive.org',
        'https://dair-community.social',
        'https://scholar.social',
        'https://pony.social',
        'https://toot.cafe',
        'https://tilde.zone',
        'https://weirder.earth',
        'https://eldritch.cafe',
        'https://ubiqueros.com',
        'https://mstdn.io',
        'https://social.joelle.us',
        'https://hackers.town',
        'https://indieweb.social',
        'https://writing.exchange',
        'https://post.lurk.org',
        'https://social.tchncs.de',
        'https://wallflowersocial.club',
        'https://todon.eu',
        'https://embracing.space',
        'https://micro.baer.works',
        'https://floss.social',
        'https://godforsaken.website',
        'https://kith.kitchen',
        'https://cybre.space',
        'https://m.nintendo.fr',
        'https://retro.social',
        'https://noeldemartin.social',
        'https://zoinks.one',
        'https://mastodon.sandwich.net',
        'https://friend.camp',
        'https://polonkai.eu',
      ],
      peers: [
        'https://1998.social',
        'https://sillyz.computer',
        'https://tychi.me',
        'https://yourlovedones.online',
        'https://y2k38.info',
      ]
    }), {
    headers: {
      'content-type': 'application/json; charset=utf-8'
    }
  })
}
