name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build People-Computer Interface
        run: deno task build-ui

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sillyz-beta # the name of the project on Deno Deploy
          entrypoint: src-edge/mod.js # the entrypoint to deploy
